#!/bin/bash

PORTS_FILE="grep_open_port_scanner"
FIRST_LINES_FROM_WORDLIST_TO_SCAN=10000
SCAN_DIRECTORY_FOR="php,txt,html,sql,db,bak"
SPIDER_FILES_EXTENSIONS="jpeg,jpg,bmp,gif,png,sql,db,txt,bak,wav,mp3,mp4"
HTTP_DEFAULT_PORT=80


### PATH OF THE OUTPUT RESULT #####
### ADD ./ FOR THE CURRENT PATH ###
OUTPUT_RESULT="/home/kali/Desktop/"

#### DIRECTORIES NAMES ###### 
NMAP_DIR_NAME="${OUTPUT_RESULT}SCAN/NMAP"
NIKTO_DIR_NAME="${OUTPUT_RESULT}SCAN/NIKTO"
TRAVERSING_DIR_NAME="${OUTPUT_RESULT}SCAN/TRAVERSING"
WEBSERVER_RESOURCES_DIR_NAME="${OUTPUT_RESULT}SCAN/WEBSERVER/RESOURCES"
WEBSERVER_WORDLIST_DIR_NAME="${OUTPUT_RESULT}SCAN/WEBSERVER/WORDLIST"

#### RESULT FILE NAMES ##### 
NMAP_OUTPUT_PORT_80="nmap-port-80-scan.nmap"
NMAP_FULL_SCAN_RESULT="full_scan_result"


### HTTP PATH FOR TRAVERSING WORDLIST #### 
PATH_TO_TRAVERSING_WORDLIST="/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"
TRAVERSING_OUTPUT_FILE_NAME="gobuster_result_scan.txt"

### NIKTO_SCAN OUTPUT FILE ####
NIKTO_OUTPUT_FILE_NAME="nikto_output_result_scan.txt"


### CEWL_WORDLIST_OUTPUT_PATH ####
CEWL_OUTPUT_FILE_NAME="wordlist.txt"
CEWL_DEPTH="3"
CEWL_MINUMUM_WORD_LENGHT="3"


#### NMAP SCAN OPTIONS ####
NMAP_SCAN_PORTSF_FROM="1-10000"
