#!/bin/bash

PORTS_FILE="grep_open_port_scanner"
FIRST_LINES_FROM_WORDLIST_TO_SCAN=10000
SCAN_DIRECTORY_FOR="php,txt,html,sql,db,bak"
SPIDER_FILES_EXTENSIONS="jpeg,jpg,bmp,gif,png,sql,db,txt,bak,wav,mp3,mp4"
HTTP_DEFAULT_PORT=80


### PATH OF THE OUTPUT RESULT #####
### LEAVE IT EMPTY FOR THE CURRENT PATH ###
OUTPUT_RESULT=""

#### DIRECTORIES NAMES ###### 
OUTPUT_FOLDER_NAME_APP_NAME="SCAN"
NMAP_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/NMAP"
NIKTO_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/NIKTO"
TRAVERSING_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/TRAVERSING"
WEBSERVER_RESOURCES_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/WEBSERVER/RESOURCES"
WEBSERVER_WORDLIST_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/WEBSERVER/WORDLIST"
WEBSERVER_SEARCHING_FOR_KEYWORDS_DIR_NAME="${OUTPUT_RESULT}${OUTPUT_FOLDER_NAME_APP_NAME}/WEBSERVER/KEYWORDS"
TEMP_DIR="/tmp"
TEMP_KEYWORDS_DIR="${TEMP_DIR}/SCAN"

#### RESULT FILE NAMES ##### 
NMAP_OUTPUT_PORT_80="nmap-port-80-scan.nmap"
NMAP_FULL_SCAN_RESULT="full_scan_result"


### HTTP PATH FOR TRAVERSING WORDLIST #### 
PATH_TO_TRAVERSING_WORDLIST="/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"
TRAVERSING_OUTPUT_FILE_NAME="gobuster_result_scan.txt"

### NIKTO_SCAN OUTPUT FILE ####
NIKTO_OUTPUT_FILE_NAME="nikto_output_result_scan.txt"


### CEWL_WORDLIST_OUTPUT_PATH ####
CEWL_OUTPUT_FILE_NAME="wordlist.txt"
CEWL_DEPTH="3"
CEWL_MINUMUM_WORD_LENGHT="3"


#### NMAP SCAN OPTIONS ####
NMAP_SCAN_PORTSF_FROM="1-10000"


### WEBSITE COMMENTS ####
WEBSERVER_SEARCH_FOR_COMMENTS_OUTPUT_FILE_NAME="tryenum_comments.txt"
WEBSERVER_SEARCH_FOR_KEYWORDS_TAGS="tryenum_hidden_user_passwords_file.txt"
WEBSERVER_SEARCH_KEYWORDS_WITH_EXTENSIONS="php,html" # please don't make changes to that line or add txt 
